// app/admin/layout.tsx
import React from "react";
import type { Metadata } from "next";
export const metadata: Metadata = {
  title: " Admin pages",
  description: "Generated by create next app",
};
import { AppSidebar } from "@/components/app-sidebar";
import { SidebarInset, SidebarProvider } from "@/components/ui/sidebar";
import Navbar from "@/components/navbar";
export default function AdminLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div className="admin-layout">
      <SidebarProvider>
        <AppSidebar />
        <SidebarInset>
          <Navbar />
          <main className="admin-content">{children}</main>
        </SidebarInset>
      </SidebarProvider>
    </div>
  );
}
